### ISSUE TITLE
Destructuring with ForContext

### ISSUE THREAD

**Issue by Karamell** [destructurama/json-net#1]
I cant' get the destruction to work with ForContext like so:
```csharp
var contextualizedLogger = leLogger.ForContext("dynamic", dynamicObject, true);
contextualizedLogger.Write("message"); // This fails
```

Is it possible to make something like this work?

**Comment by nblumhardt** [comment]
Hi @Karamell - yes, this should work. Can you please post:

* your logger configuration
* the details of what the concrete type of `dynamicObject` is (i.e. the result of `dynamicObject.GetType()`) and
* how the call fails, i.e. what you see in the log?

Cheers,
Nick

**Comment by Karamell** [comment]
This is my logger configuration:
```csharp
            var elasticsearchSink = new ElasticsearchSink(
                    new ElasticsearchSinkOptions(new Uri("http://localhost:9200"))
                    {
                        BufferBaseFilename = "./logs/buffer",
                        AutoRegisterTemplate = true
                    });
            var log = new LoggerConfiguration()
                .Destructure.JsonNetTypes()
                .WriteTo.Sink(elasticsearchSink);
```
dynamicObject.GetType returns a `Newtonsoft.Json.Linq.JObject`
the following works as expcted:
```csharp
plainLogger.Write("it's pretty json: {@whatever}", dynamicObject);
```

The error I see is an exception (nothing in the log):
`Microsoft.CSharp.RuntimeBinder.RuntimeBinderException 'object' does not contain a definition for Write`

**Comment by nblumhardt** [comment]
Aha! I see the problem :-)

```csharp
contextualizedLogger.Write("message"); // This fails
```

should be:

```csharp
contextualizedLogger.Information("message");
```

The exception is generated because `contextualizedLogger` is `dynamic` (because of the dynamic arg passed to the method that created it) and there's no method `Write()` on `ILogger`.

Cheers!

**Comment by Karamell** [comment]
Confirmed. My code is working as expected after casting the dynamic to object like so:
```csharp
var contextualizedLogger = leLogger.ForContext("dynamic", (object)dynamicObject, true);
```
