### ISSUE TITLE
Vulnerability Issue in `Microsoft.NETCore.App@1.1.2`

### ISSUE THREAD

**Issue by ali-tayebi** [destructurama/json-net#11]
Snyk.io reports a vulnerability in `Microsoft.NETCore.App@1.1.2`package referenced in your package and breaks all our builds. 

What is stopping you from removing `netcoreapp1.1` from TargetFrameworks and only rely on `netstandard2.0`? 
If it makes sense then I am happy to raise a PR.

**Comment by ali-tayebi** [comment]
Any update on this?

**Comment by nblumhardt** [comment]
Hi; since it's EOL'd I don't think there would be much harm in dropping netcoreapp1.1 now and bumping the major version of this package to 2.0.0 (`<VersionPrefix>` in the CSPROJ can be used for this). A PR would be welcome, thanks.

**Comment by ali-tayebi** [comment]
@nblumhardt  
Thanks for the reply. 

I am happy to raise that PR.

I couldn't find any documentation about contribution so I decided to create a branch and raise a PR but It seems that creating a new branch is not permitted.
Could you please check and advice.
Thanks

**Comment by nblumhardt** [comment]
Hi- to send a PR to a repository you don't have write access to, you need to create a fork; there's some info here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork - hth!

**Comment by ali-tayebi** [comment]
The corresponding PR is merged. Thank you.
When are you going to release version 2.0?

**Comment by nblumhardt** [comment]
👍 thanks!

Generally `-dev` versions are allowed to bake for a week or two to let people try them out and report issues; the best course of action will be to update your application dependencies to the `dev` version (it'll be identical to the released version in all but name), and let us know if everything is resolved successfully.
