### ISSUE TITLE
Obfuscate dynamic json by key values?

### ISSUE THREAD

**Issue by ChrisBertrand** [destructurama/json-net#15]
More of a question... The **ByIgnoring** and **attributed** projects work well with defined classes. Is there a way to sanitize/obfuscate the values within dynamic json that is returned? 

Would the following work using the ByIgnoring library? Is there a way to extend this library to do that?

**.Destructure.ByIgnoringProperties<object>(o => o.KeyValue)**

Trying to find a nice solution to this. The https://github.com/pageuppeople-opensource/SeriLog.LogSanitizingFormatter would be a good springboard but does not handle dynamic json at all.

**Comment by sungam3r** [comment]
@ChrisBertrand Hi. At the moment, nothing is obfuscated. I hope you have found a solution since the moment of asking this question. Suggestions/PRs are welcome. Closing.
