### ISSUE TITLE
Is there a way for this to support use in ForContext?

### ISSUE THREAD

**Issue by Gerboa** [destructurama/json-net#2]
Including large dynamic JSON objects in the message works but results in a large message text, trying to use a dynamic object in `ForContext` returns a `RuntimeBinderException`: 'object' does not contain a definition for 'Debug'

**Comment by nblumhardt** [comment]
Hi @Gerboa - when you call `ForContext()`, try casting the dynamic JSON object explicitly to `(object)` where it is passed:

```csharp
ForContext("Foo", (object)json, destructureObjects: true)
```

This will prevent the "dynamic" type of the argument propagating through the result, so you should get some better diagnostics. HTH!

**Comment by nblumhardt** [comment]
Closing in the understanding that you've got past the error, but please feel free to reopen if you need more help.

**Comment by Gerboa** [comment]
Yes, sorry; your answer is perfect, thanks.
