### ISSUE TITLE
Package restore failed. Rolling back package changes for 'xxx'.

### ISSUE THREAD

**Issue by StevenTCramer** [destructurama/json-net#5]
I am trying to add the nuget package to my netcoreapp1.1 project. and get the above error.

I cleared the nuget cache and still fails.

**Comment by nblumhardt** [comment]
Hi Steven - I don't think this package has been updated to work on .NET Core 1.x yet (may work on 2.0 via the compat mechanisms in place there).

A PR would be welcome if anyone is able to do the tooling update - the destructurama/attributed repository has example build scripts etc. IIRC.

Cheers,
Nick

**Comment by CumpsD** [comment]
Probably because on NuGet only the pre release versions exist which support core, while the latest stable doesnt.

Perhaps a maintainer can push a non pre-release of this repo?

**Comment by nblumhardt** [comment]
Thanks @CumpsD 👍 looks like that's the case - releasing 1.2.0 now.

**Comment by StevenTCramer** [comment]
Thanks guys :)
