### ISSUE TITLE
Objects with empty-string keys should be logged as `DictionaryValue`

### ISSUE THREAD

**Issue by nblumhardt** [destructurama/json-net#7]
Attempting to log these as `StructureValue`s as is done today fails; see:

https://github.com/serilog/serilog/issues/1127

**Comment by andrewslavin** [comment]
Any update on this?

**Comment by nblumhardt** [comment]
Hi Andrew; I'm keen to see this fixed, but I won't have any time to look at this personally in the immediate future - help via a PR would be welcome if anyone else gets an opportunity. Cheers!

**Comment by andrewslavin** [comment]
Hi @nblumhardt, I made this work with `DictionaryValue` and happy to submit a PR, just wanted to ask for some guidance. `JObject`'s property names are unique, so I can just always destructure it to a `DictionaryValue`. Or I can specifically check for an empty-string key and destructure to either  `DictionaryValue` or `StructureValue`. I can see `StructureValue` has an additional `TypeTag` property that we try to set from `JObject`, not sure how important it is to preserve this.

**Comment by andrewslavin** [comment]
@nblumhardt I also noticed this comment in the unit test:
```
            // Not currently handled correctly - will serialize as a structure
            // Assert.IsInstanceOf<DictionaryValue>(props["D"]);
```
But .Net `object` and `Dictionary` will serialise/deserialise to the same JObject, so not sure how you could tell what it was originally, and destructure it to either `StructureValue` or `DictionaryValue` correspondingly.

The options I see here for destructuring are:
1. Always use `DictionaryValue`.
1. Use `StructureValue` **whenever possible**: `DictionaryValue` if there's empty-string property, otherwise `StructureValue`.
1. Use `StructureValue` **only when needed** (and possible): `StructureValue` if there's `$type` property and there's no empty-string property, otherwise `DictionaryValue`.

Need some guidance please.

**Comment by nblumhardt** [comment]
Hi @andrewslavin - thanks for looking into this.

I think using `StructureValue` by default, and only falling back to `DictionaryValue` if we hit an invalid key, will cause the least churn/breakage with this change. Ideally, all scenarios that work today will continue to behave identically.

**Comment by andrewslavin** [comment]
Hi @nblumhardt. I've cloned the repo, created a new branch and made the changes, but cannot push. I'm doing it from Team Explorer in VS 2017. It asks me for my GitHub credentials, but then fails and logs this to the Output window:

```
Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/destructurama/json-net.git/': The requested URL returned error: 403
Pushing to https://github.com/destructurama/json-net.git
```

Do you need to grant me some permissions? Or should I be doing it differently?

**Comment by nblumhardt** [comment]
Hi Andrew - you need to use the "fork" button to create a fork of this repository, and clone that instead of this (parent) repository. Once the changes are ready on your fork, you then open a PR to send a branch from your fork to this repository. Hope this makes sense - should be some info on how to send a pull request in the GitHub docs if not. HTH, Nick

**Comment by andrewslavin** [comment]
Thanks @nblumhardt, all done!

**Comment by andrewslavin** [comment]
@nblumhardt success!

![image](https://user-images.githubusercontent.com/6835786/37323402-aee1e54c-26d7-11e8-98e0-6c22f0334130.png)

**Comment by mniak** [comment]
Any updates?

**Comment by nblumhardt** [comment]
Hi @mniak - yes, this was closed in https://github.com/destructurama/json-net/pull/8 - are you hitting the issue? If so, would it be possible to raise a new ticket? (Sorry about the confusion, I missed closing this one :-))
